jobs:
    - job: LintCode
      displayName: Lint code
      steps:
        - task: AzureCLI@2
          displayName: 'Azure CLI '
          inputs:
            azureSubscription: <service-connection-name>
            scriptType: ps
            scriptLocation: inlineScript
            inlineScript: 'az bicep build --file main.bicep'
            workingDirectory: deploy